telegram_token = 'WRITE YOURS :)'
kinopoisk_token = 'WRITE YOURS :)'
currency_url = 'https://api.exchangerate-api.com/v4/latest/USD'
yandex_api = 'WRITE YOURS :)'
weather_token = 'WRITE YOURS :)'
weather_url = 'http://api.openweathermap.org/data/2.5/weather?q={0}&appid={1}'
